name: Linguist

on:
  workflow_dispatch
  

jobs:
  linguist:
    name: Run linguist
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: RVKarmani/SensorVisualizer
          token: ${{ secrets.GH_TOKEN }}
      - uses: fabasoad/linguist-action@v1.0.0
        id: linguist
        with:
          path: './'
          percentage: true
      - name: Print linguist result
        run: echo "${{ steps.linguist.outputs.data }}"
